import Head from 'next/head';
import { CommonReactProps } from '@/types/common';
import LeftSibar from './Sidebar';
import Navbar from './Navbar';
export default function LayoutDefault({ children }: CommonReactProps): JSX.Element {
    return (
        <div className="flex flex-col w-full h-full bg-slate-800 text-white">
            <Head>
                <title>IOT-Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Navbar />
            </div>
            <div className=" flex flex-row w-full h-screen">
                <LeftSibar />
                <div className="w-full h-screen">{children}</div>
            </div>
        </div>
    );
}
